FROM ubuntu

RUN \
  apt-get update \
  && apt-get install -y dnsutils \
  && apt-get install -y python3 \
  && apt-get install -y conntrack \
  && apt-get install -y tcpdump \
  && apt-get install -y iproute2

COPY entrypoint.sh /
COPY entrypoint.py /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["google.com"]
