apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-test
  labels:
    app: dns-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-test
  template:
    metadata:
      labels:
        app: dns-test
    spec:
      containers:
      - name: ubuntu
        image: microdc/dns-utils:ubuntu-0.4.2
        command: ["/dns-utils"]
        args: ["-domain", "bitbucket.org", "-port", "8080"]
        ports:
          - containerPort: 8080
        securityContext:
          privileged: true
        resources:
          requests:
              memory: "50Mi"
              cpu: "100m"
          limits:
              memory: "50Mi"
              cpu: "100m"
      - name: alpine
        image: microdc/dns-utils:alpine-0.4.2
        command: ["/dns-utils"]
        args: ["-domain", "bitbucket.org", "-port", "8081"]
        ports:
          - containerPort: 8081
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "100m"
